# Generated by Django 4.2.4 on 2023-10-15 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutionapp', '0002_course_departmenttable_sessiontable_teacher_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='assigntable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tutionapp.sessiontable')),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tutionapp.course')),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tutionapp.departmenttable')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tutionapp.student')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tutionapp.teacher')),
            ],
        ),
    ]
