# Generated by Django 4.2.4 on 2023-10-15 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutionapp', '0003_assigntable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='student',
            name='password',
        ),
    ]
