# Generated by Django 4.2.4 on 2023-10-15 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutionapp', '0004_remove_student_last_login_remove_student_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assigntable',
            old_name='batch',
            new_name='batchid',
        ),
        migrations.RenameField(
            model_name='assigntable',
            old_name='student',
            new_name='studentid',
        ),
        migrations.RenameField(
            model_name='assigntable',
            old_name='teacher',
            new_name='teacherid',
        ),
        migrations.RemoveField(
            model_name='assigntable',
            name='course',
        ),
        migrations.RemoveField(
            model_name='assigntable',
            name='department',
        ),
        migrations.AddField(
            model_name='assigntable',
            name='courseid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tutionapp.course'),
        ),
        migrations.AddField(
            model_name='assigntable',
            name='departmentid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tutionapp.departmenttable'),
        ),
    ]
