# Generated by Django 4.2.4 on 2023-10-16 16:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutionapp', '0009_assignment_courseid'),
    ]

    operations = [
        migrations.CreateModel(
            name='notificationtable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('email', models.EmailField(max_length=255, null=True)),
                ('age', models.IntegerField()),
                ('image', models.FileField(null=True, upload_to='images')),
                ('status', models.IntegerField(null=True)),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
