# Generated by Django 4.2.4 on 2023-10-17 08:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutionapp', '0011_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='attendancetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True)),
                ('attendance', models.IntegerField(default=0, null=True)),
                ('courseid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tutionapp.course')),
                ('userid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
