# Generated by Django 4.2.4 on 2023-10-18 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutionapp', '0015_studentleave'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='studentleave',
            new_name='studentleavetable',
        ),
    ]
