# Generated by Django 4.2.4 on 2023-10-18 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutionapp', '0017_teacherleavetable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignmenttable',
            name='assignmet_id',
        ),
        migrations.AddField(
            model_name='assignmenttable',
            name='assignment_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='assignmenttable',
            name='username',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
