# Generated by Django 4.2.4 on 2023-10-18 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutionapp', '0018_remove_assignmenttable_assignmet_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmenttable',
            name='courseid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tutionapp.course'),
            preserve_default=False,
        ),
    ]
