# Generated by Django 4.2.5 on 2023-10-28 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutionapp', '0022_remove_assignmenttable_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='syallabus',
            new_name='syllabus',
        ),
        migrations.AddField(
            model_name='course',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tutionapp.departmenttable'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tutionapp.departmenttable'),
        ),
    ]
