# Generated by Django 4.2.5 on 2023-10-28 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutionapp', '0023_rename_syallabus_course_syllabus_course_department_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='syllabus',
            new_name='syallabus',
        ),
    ]
