# Generated by Django 4.2.4 on 2023-10-28 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutionapp', '0024_rename_syllabus_course_syallabus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='department',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='department',
        ),
    ]
