# Generated by Django 4.2.4 on 2023-10-28 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutionapp', '0025_remove_course_department_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='syallabus',
            new_name='syllabus',
        ),
    ]
