# Generated by Django 4.2.5 on 2023-10-31 11:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutionapp', '0027_alter_course_syllabus'),
    ]

    operations = [
        migrations.CreateModel(
            name='teachernotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('messge', models.CharField(max_length=255, null=True)),
                ('userid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='studentleavetable',
            name='userid',
        ),
        migrations.RemoveField(
            model_name='teacherleavetable',
            name='userid',
        ),
        migrations.RemoveField(
            model_name='assigntable',
            name='batchid',
        ),
        migrations.AddField(
            model_name='attendancereport',
            name='courseid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tutionapp.course'),
        ),
        migrations.DeleteModel(
            name='sessiontable',
        ),
        migrations.DeleteModel(
            name='studentleavetable',
        ),
        migrations.DeleteModel(
            name='teacherleavetable',
        ),
    ]
